version: '3'
services:
  web:
    platform: linux/amd64
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./nginx/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./src:/var/www/html
  app:
    platform: linux/amd64
    build: ./php
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
      - ./php/mail.ini:/etc/php.d/mail.ini:ro
  db:
    platform: linux/amd64
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/etc/mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
  mailhog:
        image: mailhog/mailhog
        ports:
            - 8025:8025
